[workspace]
members = [
    "shared",
    "contracts/token",
    "contracts/governance_token",
    "contracts/staking", 
    "contracts/trading",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
